name: Continuous Deployment

on:
  pull_request_target:
    types:
      - labeled
      - closed
    branches:
      - main

jobs:
  build-and-push:
    name: Build, Test, and Release
    if: contains(github.event.pull_request.labels.*.name, 'release') && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make build/resume.pdf USE_DOCKER=no
      - name: Generate release tag
        run: |
          echo "release_tag=v$(date "+%F.%H%M")" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.release_tag }}
          files: build/resume.pdf
