name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build, Test, and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          work_in_root_file_dir: true
          latexmk_use_xelatex: true
      - name: Generate release tag
        run: |
          echo "release_tag=v$(date "+%F.%H%M")" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.release_tag }}
          files: resume.pdf
